version: '3'

services:
  web:
    build: .
    expose:
      - "8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles



  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/staticfiles
    depends_on:
      - web

volumes:
  static_volume:
